"""users に age カラムを追加するテスト

Revision ID: 1ad837e7b6c8
Revises: ee936af4d3c3
Create Date: 2025-11-12 21:04:23.122860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad837e7b6c8'
down_revision: Union[str, Sequence[str], None] = 'ee936af4d3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
