"""add_summary_field_to_conversation_memory

Revision ID: 66e9ae6ccb10
Revises: d4a5af502df5
Create Date: 2025-11-18 23:23:37.114190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e9ae6ccb10'
down_revision: Union[str, Sequence[str], None] = 'd4a5af502df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_memory', sa.Column('is_summary', sa.Boolean(), nullable=False))
    op.add_column('conversation_memory', sa.Column('summary', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversation_memory_is_summary'), 'conversation_memory', ['is_summary'], unique=False)
    
    # Restore dropped indexes
    op.create_index(op.f('ix_ai_mates_public_deleted'), 'ai_mates', ['is_public', 'is_deleted'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ai_mates_user_deleted'), 'ai_mates', ['user_id', 'is_deleted'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_chat_history_mate_user'), 'chat_history', ['mate_id', 'user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_chat_history_mate_user_created'), 'chat_history', ['mate_id', 'user_id', 'created_at'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_mate_settings_mate_attribute'), 'mate_settings', ['mate_id', 'attribute_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mate_settings_mate_attribute'), table_name='mate_settings')
    op.drop_index(op.f('ix_chat_history_mate_user_created'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_mate_user'), table_name='chat_history')
    op.drop_index(op.f('ix_ai_mates_user_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_ai_mates_public_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_conversation_memory_is_summary'), table_name='conversation_memory')
    op.drop_column('conversation_memory', 'summary')
    op.drop_column('conversation_memory', 'is_summary')
    # ### end Alembic commands ###
