"""add supabase_uid to users

Revision ID: 2c52571f435c
Revises: 9d36ac38740b
Create Date: 2025-12-04 20:08:13.539076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c52571f435c'
down_revision: Union[str, Sequence[str], None] = '9d36ac38740b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_mates_public_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_ai_mates_user_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_chat_history_mate_user'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_mate_user_created'), table_name='chat_history')
    op.drop_index(op.f('ix_mate_settings_mate_attribute'), table_name='mate_settings')
    op.add_column('users', sa.Column('supabase_uid', sa.String(length=255), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_users_supabase_uid'), 'users', ['supabase_uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_supabase_uid'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'supabase_uid')
    op.create_index(op.f('ix_mate_settings_mate_attribute'), 'mate_settings', ['mate_id', 'attribute_id'], unique=False)
    op.create_index(op.f('ix_chat_history_mate_user_created'), 'chat_history', ['mate_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_mate_user'), 'chat_history', ['mate_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_ai_mates_user_deleted'), 'ai_mates', ['user_id', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_mates_public_deleted'), 'ai_mates', ['is_public', 'is_deleted'], unique=False)
    # ### end Alembic commands ###
