"""最初のテーブル作成 (Initial migration)

Revision ID: 32fbd2ad94f9
Revises: 
Create Date: 2025-11-12 20:55:24.352404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '32fbd2ad94f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_characters', 'base_prompt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_index(op.f('ix_ai_characters_is_public'), 'ai_characters', ['is_public'], unique=False)
    op.drop_constraint(op.f('ai_characters_user_id_fkey'), 'ai_characters', type_='foreignkey')
    op.create_foreign_key(None, 'ai_characters', 'users', ['user_id'], ['id'])
    op.drop_column('ai_characters', 'created_at')
    op.alter_column('character_settings', 'custom_value',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('character_settings_character_id_attribute_id_key'), 'character_settings', type_='unique')
    op.drop_index(op.f('idx_char_settings_char_id'), table_name='character_settings')
    op.drop_constraint(op.f('character_settings_attribute_id_fkey'), 'character_settings', type_='foreignkey')
    op.drop_constraint(op.f('character_settings_option_id_fkey'), 'character_settings', type_='foreignkey')
    op.drop_constraint(op.f('character_settings_character_id_fkey'), 'character_settings', type_='foreignkey')
    op.create_foreign_key(None, 'character_settings', 'm_attributes', ['attribute_id'], ['id'])
    op.create_foreign_key(None, 'character_settings', 'ai_characters', ['character_id'], ['id'])
    op.create_foreign_key(None, 'character_settings', 'm_attribute_options', ['option_id'], ['id'])
    op.alter_column('chat_history', 'message_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('chat_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_chat_history_char_id'), table_name='chat_history')
    op.drop_index(op.f('idx_chat_history_user_id'), table_name='chat_history')
    op.drop_constraint(op.f('chat_history_user_id_fkey'), 'chat_history', type_='foreignkey')
    op.drop_constraint(op.f('chat_history_character_id_fkey'), 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'ai_characters', ['character_id'], ['id'])
    op.create_foreign_key(None, 'chat_history', 'users', ['user_id'], ['id'])
    op.alter_column('m_attribute_options', 'prompt_snippet',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('idx_options_attr_id'), table_name='m_attribute_options')
    op.create_index(op.f('ix_m_attribute_options_option_value'), 'm_attribute_options', ['option_value'], unique=False)
    op.drop_constraint(op.f('m_attribute_options_attribute_id_fkey'), 'm_attribute_options', type_='foreignkey')
    op.create_foreign_key(None, 'm_attribute_options', 'm_attributes', ['attribute_id'], ['id'])
    op.alter_column('m_attributes', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('99'))
    op.drop_constraint(op.f('m_attributes_attribute_key_key'), 'm_attributes', type_='unique')
    op.create_index(op.f('ix_m_attributes_attribute_key'), 'm_attributes', ['attribute_key'], unique=True)
    op.alter_column('users', 'profile',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'profile',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_m_attributes_attribute_key'), table_name='m_attributes')
    op.create_unique_constraint(op.f('m_attributes_attribute_key_key'), 'm_attributes', ['attribute_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('m_attributes', 'display_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('99'))
    op.drop_constraint(None, 'm_attribute_options', type_='foreignkey')
    op.create_foreign_key(op.f('m_attribute_options_attribute_id_fkey'), 'm_attribute_options', 'm_attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_m_attribute_options_option_value'), table_name='m_attribute_options')
    op.create_index(op.f('idx_options_attr_id'), 'm_attribute_options', ['attribute_id'], unique=False)
    op.alter_column('m_attribute_options', 'prompt_snippet',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key(op.f('chat_history_character_id_fkey'), 'chat_history', 'ai_characters', ['character_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_history_user_id_fkey'), 'chat_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_history_char_id'), 'chat_history', ['character_id'], unique=False)
    op.alter_column('chat_history', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_history', 'message_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'character_settings', type_='foreignkey')
    op.drop_constraint(None, 'character_settings', type_='foreignkey')
    op.drop_constraint(None, 'character_settings', type_='foreignkey')
    op.create_foreign_key(op.f('character_settings_character_id_fkey'), 'character_settings', 'ai_characters', ['character_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('character_settings_option_id_fkey'), 'character_settings', 'm_attribute_options', ['option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('character_settings_attribute_id_fkey'), 'character_settings', 'm_attributes', ['attribute_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_char_settings_char_id'), 'character_settings', ['character_id'], unique=False)
    op.create_unique_constraint(op.f('character_settings_character_id_attribute_id_key'), 'character_settings', ['character_id', 'attribute_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('character_settings', 'custom_value',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('ai_characters', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_characters', type_='foreignkey')
    op.create_foreign_key(op.f('ai_characters_user_id_fkey'), 'ai_characters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_characters_is_public'), table_name='ai_characters')
    op.alter_column('ai_characters', 'base_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
