"""add_is_deleted_to_users

Revision ID: 377177659685
Revises: 696623cf81c3
Create Date: 2025-11-18 21:20:24.309046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '377177659685'
down_revision: Union[str, Sequence[str], None] = '696623cf81c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_mate_id'), table_name='ai_mates', postgresql_where='(mate_id IS NOT NULL)')
    op.drop_index(op.f('ix_ai_characters_is_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_ai_characters_is_public'), table_name='ai_mates')
    op.create_index(op.f('ix_ai_mates_is_deleted'), 'ai_mates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_mates_is_public'), 'ai_mates', ['is_public'], unique=False)
    op.create_index(op.f('ix_ai_mates_mate_id'), 'ai_mates', ['mate_id'], unique=True)
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_mate_id'), 'chat_history', ['mate_id'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.alter_column('m_attributes', 'prompt_template',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # 既存ユーザーのために nullable=True で先に追加し、デフォルト値を設定
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # 既存データに対してデフォルト値 False を設定
    op.execute('UPDATE users SET is_deleted = FALSE WHERE is_deleted IS NULL')
    # その後、NOT NULL 制約を追加
    op.alter_column('users', 'is_deleted',
               existing_type=sa.Boolean(),
               nullable=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_column('users', 'is_deleted')
    op.alter_column('m_attributes', 'prompt_template',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_mate_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_index(op.f('ix_ai_mates_mate_id'), table_name='ai_mates')
    op.drop_index(op.f('ix_ai_mates_is_public'), table_name='ai_mates')
    op.drop_index(op.f('ix_ai_mates_is_deleted'), table_name='ai_mates')
    op.create_index(op.f('ix_ai_characters_is_public'), 'ai_mates', ['is_public'], unique=False)
    op.create_index(op.f('ix_ai_characters_is_deleted'), 'ai_mates', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_mate_id'), 'ai_mates', ['mate_id'], unique=True, postgresql_where='(mate_id IS NOT NULL)')
    # ### end Alembic commands ###
