"""add_conversation_memory_with_pgvector

Revision ID: d4a5af502df5
Revises: 8ffd66a8d28f
Create Date: 2025-11-18 23:18:50.842154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a5af502df5'
down_revision: Union[str, Sequence[str], None] = '8ffd66a8d28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_memory',
    sa.Column('mate_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_message', sa.String(), nullable=False),
    sa.Column('message_role', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.String(), nullable=True),  # JSON string format for vector storage
    sa.Column('embedded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mate_id'], ['ai_mates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_memory_embedded_at'), 'conversation_memory', ['embedded_at'], unique=False)
    op.create_index(op.f('ix_conversation_memory_mate_id'), 'conversation_memory', ['mate_id'], unique=False)
    op.create_index(op.f('ix_conversation_memory_user_id'), 'conversation_memory', ['user_id'], unique=False)
    
    # Restore dropped indexes (prevent loss of performance)
    op.create_index(op.f('ix_ai_mates_public_deleted'), 'ai_mates', ['is_public', 'is_deleted'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ai_mates_user_deleted'), 'ai_mates', ['user_id', 'is_deleted'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_chat_history_mate_user'), 'chat_history', ['mate_id', 'user_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_chat_history_mate_user_created'), 'chat_history', ['mate_id', 'user_id', 'created_at'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_mate_settings_mate_attribute'), 'mate_settings', ['mate_id', 'attribute_id'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mate_settings_mate_attribute'), table_name='mate_settings')
    op.drop_index(op.f('ix_chat_history_mate_user_created'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_mate_user'), table_name='chat_history')
    op.drop_index(op.f('ix_ai_mates_user_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_ai_mates_public_deleted'), table_name='ai_mates')
    op.drop_index(op.f('ix_conversation_memory_user_id'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_mate_id'), table_name='conversation_memory')
    op.drop_index(op.f('ix_conversation_memory_embedded_at'), table_name='conversation_memory')
    op.drop_table('conversation_memory')
    # ### end Alembic commands ###
